#
# Copyright (C) 2020-2023 Université Grenoble Alpes, ANS Innovation
#

APPLICATION=driver_stts751

#QUIET = 1
#CFLAGS_DBG = 

EXTERNAL_MODULE_DIRS += ../../modules/
USEMODULE += stts751

USEMODULE += xtimer
USEMODULE += shell

USEMODULE += printf_float


include $(RIOTBASE)/Makefile.include


