#!/bin/bash

QUERY='[.features[] | { lat1:.geometry.coordinates[0][0][0], lon1:.geometry.coordinates[0][0][1],  lat2:.geometry.coordinates[0][2][0], lon2:.geometry.coordinates[0][2][1]} ]'

jq "$QUERY" geofence.geosjon | json2csv --no-header > geofence.csv
echo "" >> geofence.csv

csv2c() {
    WHOAMI=$(whoami)
    NOW=$(date '+%Y-%m-%d %H:%M:%S')

    echo "/* Generated by $WHOAMI at $NOW */"

    echo '#include "geofence.h"'

    echo 'static const Area_t geofence_retangles[] = {'

    while read -r line; do
        echo -e "\t{ $line },"
    done < $1 

    echo '};'
}

csv2c geofence.csv > geofence_rectangles.h
