
# Debug

ENABLE_DEBUG_MISSION ?= 0
ENABLE_DEBUG_REPEAT ?= 1
ENABLE_DEBUG_RANGING ?= 1
ENABLE_DEBUG_TELEMETRY ?= 1
ENABLE_DEBUG_APRS ?= 1
ENABLE_DEBUG_EWSS ?= 1

CFLAGS += -DENABLE_DEBUG_MISSION=$(ENABLE_DEBUG_MISSION)
CFLAGS += -DENABLE_DEBUG_REPEAT=$(ENABLE_DEBUG_REPEAT)
CFLAGS += -DENABLE_DEBUG_RANGING=$(ENABLE_DEBUG_RANGING)
CFLAGS += -DENABLE_DEBUG_TELEMETRY=$(ENABLE_DEBUG_TELEMETRY)
CFLAGS += -DENABLE_DEBUG_APRS=$(ENABLE_DEBUG_APRS)
CFLAGS += -DENABLE_DEBUG_EWSS=$(ENABLE_DEBUG_EWSS)

# Debug SX1302 driver
DEBUG_FTIME ?= 0
DEBUG_HAL ?= 0
DEBUG_CMD ?= 0
ENABLE_DEBUG_LGW_UTILS ?= 1

CFLAGS += -DDEBUG_FTIME=$(DEBUG_FTIME)
CFLAGS += -DDEBUG_HAL=$(DEBUG_HAL)
CFLAGS += -DDEBUG_CMD=$(DEBUG_CMD)
CFLAGS += -DENABLE_DEBUG_LGW_UTILS=$(ENABLE_DEBUG_LGW_UTILS)


# Set this to 1 to enable code in RIOT that does safety checking
# which is not needed in a production environment but helps in the
# development process:
DEVELHELP ?= 1

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

#CFLAGS += -DENABLE_DEBUG=1
CFLAGS += -DDEBUG_ASSERT_VERBOSE=1
