# Meshtastic

USEMODULE += meshtastic_utils

CFLAGS += -DMESHTASTIC=$(MESHTASTIC)

MESHTASTIC_FREQUENCY ?= 869525000
MESHTASTIC_RF_POWER ?= 27
MESHTASTIC_PREAMBLE_LEN ?= 16
MESHTASTIC_CODING_RATE ?= (8-4)


CFLAGS += -DMESHTASTIC_FREQUENCY=$(MESHTASTIC_FREQUENCY)
CFLAGS += -DMESHTASTIC_RF_POWER=$(MESHTASTIC_RF_POWER)
CFLAGS += -DMESHTASTIC_PREAMBLE_LEN=$(MESHTASTIC_PREAMBLE_LEN)
CFLAGS += -DMESHTASTIC_CODING_RATE=$(MESHTASTIC_CODING_RATE)
