

INVOKE_CALLBACKS ?= 1
PERIODIC_CALLBACK_IN_SEC ?= 10

CFLAGS += -DINVOKE_CALLBACKS=$(INVOKE_CALLBACKS)
CFLAGS += -DPERIODIC_CALLBACK_IN_SEC=$(PERIODIC_CALLBACK_IN_SEC)


# Period for RTC resync with GNSS (TODO)

# Resync every 30 minutes
MISSION_RTC_RESYNC_PERIOD_SEC ?= 1800


# Transmit parameters

MISSION_PREAMBLE_LEN ?= 8
MISSION_SF ?= 7
MISSION_RF_POWER ?= 12

CFLAGS += -DMISSION_PREAMBLE_LEN=$(MISSION_PREAMBLE_LEN)
CFLAGS += -DMISSION_SF=$(MISSION_SF)
CFLAGS += -DMISSION_RF_POWER=$(MISSION_RF_POWER)


# Period for ranging


# Period for telemetry

