

INVOKE_CALLBACKS ?= 1
PERIODIC_CALLBACK_IN_SEC ?= 10

CFLAGS += -DINVOKE_CALLBACKS=$(INVOKE_CALLBACKS)
CFLAGS += -DPERIODIC_CALLBACK_IN_SEC=$(PERIODIC_CALLBACK_IN_SEC)

# Period for ranging

# Period for telemetry
