USEMODULE += lora_mesh

CHIRPSTACK_MESH_RELAY_ID ?= 0xdeafbeefU

CHIRPSTACK_MESH_SIGNING_KEY ?= {0xca, 0xfe, 0xba, 0xbe, 0x12, 0x34, 0x56, 0x78, 0xca, 0xfe, 0xba, 0xbe, 0x12, 0x34, 0x56, 0x78}

CHIRPSTACK_MESH_MAX_HOP ?= 2

CHIRPSTACK_MESH_DR ?= 5

CHIRPSTACK_MESH_TXPOWER ?= 16

CHIRPSTACK_MESH_CHANNELS ?= {867.1, 867.3, 867.5, 867.7, 867.9, 868.1, 868.3, 868.5}

CFLAGS += -DCHIRPSTACK_MESH_RELAY_ID=$(CHIRPSTACK_MESH_RELAY_ID)
CFLAGS += -DCHIRPSTACK_MESH_SIGNING_KEY=$(CHIRPSTACK_MESH_SIGNING_KEY)
CFLAGS += -DCHIRPSTACK_MESH_MAX_HOP=$(CHIRPSTACK_MESH_MAX_HOP)
CFLAGS += -DCHIRPSTACK_MESH_DR=$(CHIRPSTACK_MESH_DR)
CFLAGS += -DCHIRPSTACK_MESH_TXPOWER=$(CHIRPSTACK_MESH_TXPOWER)
CFLAGS += -DCHIRPSTACK_MESH_CHANNELS=$(CHIRPSTACK_MESH_CHANNELS)

