
# Chirpstack Mesh

REPEAT_FILTER_SNR_THRESHOLD ?= 0

# All
#REPEAT_FILTER_DEVADDR_SUBNET ?= 0x00000000U
#REPEAT_FILTER_DEVADDR_MASK ?= 0x00000000U

# CampusIoT
REPEAT_FILTER_DEVADDR_SUBNET ?= 0xfc00ac00U
REPEAT_FILTER_DEVADDR_MASK ?= 0xfffffc00U

#REPEAT_FILTER_JOINEUI_SUBNET ?= TODO
#REPEAT_FILTER_JOINEUI_MASK ?= TODO


CFLAGS += -DREPEAT_FILTER_SNR_THRESHOLD=$(REPEAT_FILTER_SNR_THRESHOLD)
CFLAGS += -DREPEAT_FILTER_DEVADDR_SUBNET=$(REPEAT_FILTER_DEVADDR_SUBNET)
CFLAGS += -DREPEAT_FILTER_DEVADDR_MASK=$(REPEAT_FILTER_DEVADDR_MASK)


REPEAT_TXPOWER ?= 16
REPEAT_DR ?= 5
REPEAT_SF ?= 7
# BW 0x04 --> 125000 Hz
REPEAT_BW ?= 4

CFLAGS += -DREPEAT_TXPOWER=$(REPEAT_TXPOWER)
CFLAGS += -DREPEAT_DR=$(REPEAT_DR)
CFLAGS += -DREPEAT_SF=$(REPEAT_SF)
CFLAGS += -DREPEAT_BW=$(REPEAT_BW)

# Chirpstack Mesh

CHIRPSTACK_MESH_ENABLE ?= 0
ifeq ($(CHIRPSTACK_MESH_ENABLE),1)
include "Makefile.loramesh.mk"
endif

