
# Chirpstack Mesh

REPEAT_FILTER_SNR_THRESHOLD ?= 0

# All
#REPEAT_FILTER_DEVADDR_SUBNET ?= 0x00000000U
#REPEAT_FILTER_DEVADDR_MASK ?= 0x00000000U

# CampusIoT
REPEAT_FILTER_DEVADDR_SUBNET ?= 0xfc00ac00U
REPEAT_FILTER_DEVADDR_MASK ?= 0xfffffc00U

#REPEAT_FILTER_JOINEUI_SUBNET ?= TODO
#REPEAT_FILTER_JOINEUI_MASK ?= TODO


CFLAGS += -DREPEAT_FILTER_SNR_THRESHOLD=$(REPEAT_FILTER_SNR_THRESHOLD)
CFLAGS += -DREPEAT_FILTER_DEVADDR_SUBNET=$(REPEAT_FILTER_DEVADDR_SUBNET)
CFLAGS += -DREPEAT_FILTER_DEVADDR_MASK=$(REPEAT_FILTER_DEVADDR_MASK)


REPEAT_TXPOWER ?= 16
REPEAT_DR ?= 5
REPEAT_SF ?= 7
# BW 0x04 --> 125000 Hz
REPEAT_BW ?= 4

CFLAGS += -DREPEAT_TXPOWER=$(REPEAT_TXPOWER)
CFLAGS += -DREPEAT_DR=$(REPEAT_DR)
CFLAGS += -DREPEAT_SF=$(REPEAT_SF)
CFLAGS += -DREPEAT_BW=$(REPEAT_BW)


# Chirpstack Mesh

USEMODULE += lora_mesh

CHIRPSTACK_MESH_ENABLE ?= 1

CHIRPSTACK_MESH_RELAY_ID ?= 0xdeadbeefU

CHIRPSTACK_MESH_SIGNING_KEY ?= \{0xca,0xfe,0xba,0xbe,0x12,0x34,0x56,0x78,0xca,0xfe,0xba,0xbe,0x12,0x34,0x56,0x78\}

CHIRPSTACK_MESH_MAX_HOP ?= 2


CHIRPSTACK_MESH_CHANNELS ?= \{868100000,868300000,868500000,867100000,867300000,867500000,867700000,867900000}\

CFLAGS += -DCHIRPSTACK_MESH_ENABLE=$(CHIRPSTACK_MESH_ENABLE)
CFLAGS += -DCHIRPSTACK_MESH_RELAY_ID=$(CHIRPSTACK_MESH_RELAY_ID)
CFLAGS += -DCHIRPSTACK_MESH_SIGNING_KEY=$(CHIRPSTACK_MESH_SIGNING_KEY)
CFLAGS += -DCHIRPSTACK_MESH_MAX_HOP=$(CHIRPSTACK_MESH_MAX_HOP)
CFLAGS += -DCHIRPSTACK_MESH_CHANNELS=$(CHIRPSTACK_MESH_CHANNELS)

