

INVOKE_CALLBACKS ?= 1

ifeq ($(PROD),1)
PERIODIC_CALLBACK_IN_SEC ?= 20
else
PERIODIC_CALLBACK_IN_SEC ?= 10
endif

CFLAGS += -DINVOKE_CALLBACKS=$(INVOKE_CALLBACKS)
CFLAGS += -DPERIODIC_CALLBACK_IN_SEC=$(PERIODIC_CALLBACK_IN_SEC)


# Period for RTC resync with GNSS (TODO)

# Resync every 30 minutes
MISSION_RTC_RESYNC_PERIOD_SEC ?= 1800


# Transmit parameters

MISSION_PREAMBLE_LEN ?= 8
MISSION_SF ?= 7
MISSION_RF_POWER ?= 12

CFLAGS += -DMISSION_PREAMBLE_LEN=$(MISSION_PREAMBLE_LEN)
CFLAGS += -DMISSION_SF=$(MISSION_SF)
CFLAGS += -DMISSION_RF_POWER=$(MISSION_RF_POWER)

# List of message types to send periodically

# TODO add STAT_PAYLOAD
MISSION_MESSAGES_TYPE ?= \{RANGE1_PAYLOAD,TELEMETRY_PAYLOAD,APRS_LORAWAN_PAYLOAD,APRS_AX25_PAYLOAD,TELEMETRY_PAYLOAD,EWSS_PAYLOAD}\

# Every 4 LoRaWAN frames (TODO not implemented)
MISSION_XOR_REDUNDANCY ?= 4

# 122 bit-long message for alerting forest fire (in the south west of France)
MISSION_EWSS_PAYLOAD ?= \{0xde,0xad,0xbe,0xef,0xca,0xfe,0xba,0xbe,0xde,0xad,0xbe,0xef,0xca,0xfe,0xba,0xbe}\


ifeq ($(PROD),1)
# TinyGS Parameters for EU868 (APRS AX25 frame)
# {"mode":"LoRa","sat":"Default","freq":869.525,"bw":125,"pl":8,"pwr":0,"sf":11,"cr":5,"sw":18,"crc":true,"fldro":0,"cl":0,"gain":0}
TINYGS_FREQUENCY ?= 869525000
TINYGS_BANDWIDTH ?= 125000
TINYGS_SPREADING_FACTOR ?= 11
TINYGS_CODING_RATE ?= (5-4)
TINYGS_SYNCWORD ?= 18
TINYGS_PREAMBLE_LEN ?= 18
TINYGS_RF_POWER ?= 27

CFLAGS += -DMISSION_APRS_FREQUENCY="$(TINYGS_FREQUENCY)"
CFLAGS += -DMISSION_APRS_BANDWIDTH="$(TINYGS_BANDWIDTH)"
CFLAGS += -DMISSION_APRS_SPREADING_FACTOR="$(TINYGS_SPREADING_FACTOR)"
CFLAGS += -DMISSION_APRS_CODING_RATE="$(TINYGS_CODING_RATE)"
CFLAGS += -DMISSION_APRS_SYNCWORD="$(TINYGS_SYNCWORD)"
CFLAGS += -DMISSION_APRS_PREAMBLE_LEN="$(TINYGS_PREAMBLE_LEN)"
CFLAGS += -DMISSION_APRS_RF_POWER="$(TINYGS_RF_POWER)"
else
CFLAGS += -DMISSION_APRS_FREQUENCY="$(TINYGS_FREQUENCY)"
CFLAGS += -DMISSION_APRS_BANDWIDTH="$(TINYGS_BANDWIDTH)"
CFLAGS += -DMISSION_APRS_SPREADING_FACTOR="$(TINYGS_SPREADING_FACTOR)"
CFLAGS += -DMISSION_APRS_CODING_RATE="$(TINYGS_CODING_RATE)"
CFLAGS += -DMISSION_APRS_SYNCWORD="$(TINYGS_SYNCWORD)"
CFLAGS += -DMISSION_APRS_PREAMBLE_LEN="$(TINYGS_PREAMBLE_LEN)"
CFLAGS += -DMISSION_APRS_RF_POWER="$(TINYGS_RF_POWER)"
endif

# -11 est souvent utilisé pour les ballons
MISSION_APRS_CALLSIGN ?= \"FCSUG\"
MISSION_APRS_COMMENT ?= \"Balloon Thingsat 1\"

CFLAGS += -DMISSION_MESSAGES_TYPE=$(MISSION_MESSAGES_TYPE)
CFLAGS += -DMISSION_XOR_REDUNDANCY=$(MISSION_XOR_REDUNDANCY)
CFLAGS += -DMISSION_EWSS_PAYLOAD=$(MISSION_EWSS_PAYLOAD)

CFLAGS += -DMISSION_APRS_CALLSIGN="$(MISSION_APRS_CALLSIGN)"
CFLAGS += -DMISSION_APRS_COMMENT="$(MISSION_APRS_COMMENT)"

# For APRS snprintf
#CFLAGS += -Wno-format-overflow
#CFLAGS += -Wno-format-truncation


# If ENDPOINT_DEVADDR is defined, ENDPOINT_DEVADDR replace the devaddr defined for the SX130x EUI of the concentrator
# ENDPOINT_DEVADDR ?= 0xfc001234
# ENDPOINT_GWEUI ?= 0x0000000000000000
# ENDPOINT_NWKSKEY ?= \{0xBA,0xBE,0xCA,0xFE,0x12,0x34,0x56,0x78,0xBA,0xBE,0xCA,0xFE,0x12,0x34,0x56,0x78\}
# ENDPOINT_APPSKEY ?= \{0xCA,0xFE,0xBA,0xBE,0x12,0x34,0x56,0x78,0xCA,0xFE,0xBA,0xBE,0x12,0x34,0x56,0x78\}
# CFLAGS += -DENDPOINT_DEVADDR=$(ENDPOINT_DEVADDR)
# CFLAGS += -DENDPOINT_GWEUI=$(ENDPOINT_GWEUI)
# CFLAGS += -DENDPOINT_NWKSKEY=$(ENDPOINT_NWKSKEY)
# CFLAGS += -DENDPOINT_APPSKEY=$(ENDPOINT_APPSKEY)

