
# Ranging

RANGING_TXPOWER ?= 16
RANGING_DR ?= 5
RANGING_SF ?= 7
# BW 0x04 --> 125000 Hz
RANGING_BW ?= 4

CFLAGS += -DRANGING_TXPOWER=$(RANGING_TXPOWER)
CFLAGS += -DRANGING_DR=$(RANGING_DR)
CFLAGS += -DRANGING_SF=$(RANGING_SF)
CFLAGS += -DRANGING_BW=$(RANGING_BW)

