# MeshCore

USEMODULE += meshcore_utils

CFLAGS += -DMESHCORE_ENABLE=$(MESHCORE_ENABLE)


# EU/UK "classic" community preset : 869.525 MHz, BW 250 kHz, SF11, CR 4/5, syncword 0x12
# Nota Bene: the SX1302/SX1303 concentrator cannot demodulate the newer
# 62.5 kHz EU preset (869.618 MHz) : only BW 125/250/500 kHz are supported.
MESHCORE_FREQUENCY ?= 869525000U
MESHCORE_BANDWIDTH ?= 250000U
MESHCORE_SPREADING_FACTOR ?= 11U

# 16 symbols for SF > 8, 32 symbols for SF <= 8 (cf RadioLibWrappers.h)
MESHCORE_PREAMBLE_LEN ?= 16U
# CR 4/5
MESHCORE_CODING_RATE ?= 1U
# RadioLib private syncword (MeshCore does not override it)
MESHCORE_SYNCWORD ?= 0x12U
MESHCORE_RF_POWER ?= 27U

# Repeater identity : first byte of the node public key (node hash)
MESHCORE_SELF_HASH ?= 0xC5U

# Frames with a hop count higher or equal are not repeated
MESHCORE_MAX_HOP ?= 8U


CFLAGS += -DMESHCORE_FREQUENCY=$(MESHCORE_FREQUENCY)
CFLAGS += -DMESHCORE_RF_POWER=$(MESHCORE_RF_POWER)
CFLAGS += -DMESHCORE_PREAMBLE_LEN=$(MESHCORE_PREAMBLE_LEN)
CFLAGS += -DMESHCORE_CODING_RATE=$(MESHCORE_CODING_RATE)
CFLAGS += -DMESHCORE_BANDWIDTH=$(MESHCORE_BANDWIDTH)
CFLAGS += -DMESHCORE_SPREADING_FACTOR=$(MESHCORE_SPREADING_FACTOR)
CFLAGS += -DMESHCORE_SYNCWORD=$(MESHCORE_SYNCWORD)
CFLAGS += -DMESHCORE_SELF_HASH=$(MESHCORE_SELF_HASH)
CFLAGS += -DMESHCORE_MAX_HOP=$(MESHCORE_MAX_HOP)
