# Meshtastic

USEMODULE += meshtastic_utils

CFLAGS += -DMESHTASTIC_ENABLE=$(MESHTASTIC_ENABLE)


# For Long Moderate
MESHTASTIC_FREQUENCY ?= 869462500U
MESHTASTIC_BANDWIDTH ?= 125000U
MESHTASTIC_SPREADING_FACTOR ?= 11U

MESHTASTIC_PREAMBLE_LEN ?= 16U
# CR 4/8
MESHTASTIC_CODING_RATE ?= 4U
MESHTASTIC_SYNCWORD ?= 0x2bU
MESHTASTIC_RF_POWER ?= 27U



CFLAGS += -DMESHTASTIC_FREQUENCY=$(MESHTASTIC_FREQUENCY)
CFLAGS += -DMESHTASTIC_RF_POWER=$(MESHTASTIC_RF_POWER)
CFLAGS += -DMESHTASTIC_PREAMBLE_LEN=$(MESHTASTIC_PREAMBLE_LEN)
CFLAGS += -DMESHTASTIC_CODING_RATE=$(MESHTASTIC_CODING_RATE)
CFLAGS += -DMESHTASTIC_BANDWIDTH=$(MESHTASTIC_BANDWIDTH)
CFLAGS += -DMESHTASTIC_SPREADING_FACTOR=$(MESHTASTIC_SPREADING_FACTOR)
CFLAGS += -DMESHTASTIC_SYNCWORD=$(MESHTASTIC_SYNCWORD)
