
# Debug

ENABLE_DEBUG_MISSION ?= 1
ENABLE_DEBUG_REPEAT ?= 1
ENABLE_DEBUG_RANGING ?= 1
ENABLE_DEBUG_TELEMETRY ?= 1
ENABLE_DEBUG_APRS ?= 1
ENABLE_DEBUG_EWSS ?= 1


CFLAGS += -DENABLE_DEBUG_MISSION=$(ENABLE_DEBUG_MISSION)
CFLAGS += -DENABLE_DEBUG_REPEAT=$(ENABLE_DEBUG_REPEAT)
CFLAGS += -DENABLE_DEBUG_RANGING=$(ENABLE_DEBUG_RANGING)
CFLAGS += -DENABLE_DEBUG_TELEMETRY=$(ENABLE_DEBUG_TELEMETRY)
CFLAGS += -DENABLE_DEBUG_APRS=$(ENABLE_DEBUG_APRS)
CFLAGS += -DENABLE_DEBUG_EWSS=$(ENABLE_DEBUG_EWSS)


# Set this to 1 to enable code in RIOT that does safety checking
# which is not needed in a production environment but helps in the
# development process:
DEVELHELP ?= 1

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

#CFLAGS += -DENABLE_DEBUG=1
CFLAGS += -DDEBUG_ASSERT_VERBOSE=1
